version: 2.1
jobs:
  build-from-docker:
    docker:
      - image: adematti/obiwan:DR9
    steps:
      - run:
          name: CPU info
          command: cat /proc/cpuinfo
      - checkout
      - run:
          name: Tests
          no_output_timeout: 30m
          command: |
              cd py
              export PYTHONPATH=${PYTHONPATH}:$(pwd)
              coverage run tests/test_runbrick_legacypipe.py
              coverage run -a -m pytest tests/

workflows:
  main:
    jobs:
      - build-from-docker
